# Generated by Django 3.1.7 on 2021-07-08 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consultas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=2000)),
                ('clima', models.CharField(max_length=2000)),
                ('humedad', models.CharField(max_length=2000)),
                ('temp_min', models.CharField(max_length=2000)),
                ('temp_max', models.CharField(max_length=2000)),
            ],
        ),
    ]
